### ISSUE TITLE
Virtuoso result set size is limited to 1048576 results 

### ISSUE THREAD

**Issue by vpapako** [hobbit-project/versioning-benchmark#11]
There are queries asking for full versions materialization and VOS imposes a limit of 1048576 results on HTTP responses (https://github.com/openlink/virtuoso-opensource/issues/700).
So I have to find another way for computing expected results with or without Virtuoso.

**Comment by MichaelRoeder** [comment]
Does the problem occur even if you use pagination (i.e., use limit and offset to ask for a certain subset of the result, e.g., https://stackoverflow.com/questions/27488403/paginating-sparql-results)?

If you use a SPARQL library, it should support pagination :wink:

**Comment by vpapako** [comment]
I was trying to fix it by working on Virtuoso over JDBC connection, but using pagination sounds like a good idea too :)
